# Generated by Django 5.1.3 on 2024-12-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='2024-12-17T16:44:12+03:00')),
                ('game_length', models.IntegerField(default=30, help_text='Seconds per single game/session')),
                ('target_size', models.IntegerField(default=3, help_text='Target size')),
                ('total_target', models.IntegerField(default=7, help_text='Total targets on screen')),
                ('target_hit', models.IntegerField(default=0, help_text='Total target hit')),
                ('mode', models.CharField(choices=[('C', 'Challenge'), ('CH', 'Chill')], default='CH', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
