# Generated by Django 5.1.3 on 2025-01-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='2025-01-06T13:16:23+03:00')),
                ('game_length', models.IntegerField(default=30, help_text='Seconds per single game/session')),
                ('target_size', models.IntegerField(default=3, help_text='Target size')),
                ('total_target', models.IntegerField(default=7, help_text='Total targets on screen')),
                ('target_hit', models.IntegerField(default=0, help_text='Total target hit')),
                ('mode', models.CharField(choices=[('C', 'Challenge'), ('CH', 'Chill')], default='CH', max_length=2)),
            ],
        ),
    ]
