# Generated by Django 5.1.3 on 2025-02-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_click',
            field=models.BooleanField(default=False, help_text='Mouse click to hit'),
        ),
        migrations.AddField(
            model_name='score',
            name='sensitivity',
            field=models.IntegerField(default=1, help_text='Mouse sensitivity'),
        ),
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(default='2025-02-28T18:35:59+03:00'),
        ),
    ]
