version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
